export const ADD_ITEM = 'ADD_ITEM';
export const ADD_PERSON = 'ADD_PERSON';

export const SET_ITEM = 'SET_ITEM';
export const UNSET_ITEM = 'UNSET_ITEM';

export const CHANGE_CONTEXT_ITEM_DATA = 'CHANGE_CONTEXT_ITEM_DATA';
export const CHANGE_CONTEXT_NAME_DATA = 'CHANGE_CONTEXT_NAME_DATA';

export const CALCULATE_TOTAL = 'CALCULATE_TOTAL';

export const ADD_PERSON_TO_SPLIT = 'ADD_PERSON_TO_SPLIT';
export const REMOVE_PERSON_FROM_SPLIT = 'REMOVE_PERSON_FROM_SPLIT';

export const DELETE_ITEM = 'DELETE_ITEM';
export const DELETE_PERSON = 'DELETE_PERSON';

export const RECALCULATE = 'RECALCULATE';

export const REWRITE_CLIPBOARD_CONTENT = "REWRITE_CLIPBOARD_CONTENT";

export const CHANGE_TAX = 'CHANGE_TAX'
export const CHANGE_TIP = 'CHANGE_TIP'
export const CHANGE_SPLIT_METHOD = 'CHANGE_SPLIT_METHOD'

export const TOGGLE_CONFIRM = 'TOGGLE_CONFIRM';
